### ISSUE TITLE
mac brew install  

### ISSUE THREAD

**Issue by Xu1Z** [rofl0r/proxychains-ng#446] opened 2022-04-28 14:26 UTC
➜  ~ proxychains4

Usage:	/opt/homebrew/bin/proxychains4 -q -f config_file program_name [arguments]
	-q makes proxychains quiet - this overrides the config setting
	-f allows one to manually specify a configfile to use
	for example : proxychains telnet somehost.com
More help in README file

--------------------------------------------

➜  ~ proxychains4 curl www.google.com
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
dyld[95853]: terminating because inserted dylib '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' could not be loaded: tried: '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/usr/local/lib/libproxychains4.dylib' (no such file), '/usr/lib/libproxychains4.dylib' (no such file)
dyld[95853]: tried: '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/usr/local/lib/libproxychains4.dylib' (no such file), '/usr/lib/libproxychains4.dylib' (no such file)
[1]    95853 abort      /opt/homebrew/bin/proxychains4 curl www.google.com
:(

**Comment by rofl0r** [comment] 2022-04-28 14:45
duplicate of https://github.com/rofl0r/proxychains-ng/issues/433

**Comment by Xu1Z** [comment] 2022-04-28 14:45
> 

no 不行

**Closed by rofl0r** 2022-04-28 14:45 UTC
