### ISSUE TITLE
version 4.16 doesn't works on macOS m1 Ventura 13.0

### ISSUE THREAD

**Issue by netcan** [rofl0r/proxychains-ng#484] opened 2022-11-03 15:41 UTC
there is the log:
```
time proxychains4 curl google.com
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
curl: (28) Failed to connect to google.com port 80 after 75007 ms: Operation timed out
proxychains4 curl google.com  0.01s user 0.01s system 0% cpu 1:15.02 total
```

it blocked at preloading.

**Comment by rofl0r** [comment] 2022-11-04 09:36
you need to disable SIP.

**Comment by netcan** [comment] 2022-11-04 13:04
I have disabled SIP. but it cannot detect the correct arch. 

```
proxychains4 curl google.com
[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
dyld[6008]: terminating because inserted dylib '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' could not be loaded: tried: '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (no such file), '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need ''))
dyld[6008]: tried: '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (no such file), '/opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need ''))
zsh: abort      proxychains4 curl google.com
```

**but is an incompatible architecture (have 'arm64', need '')**

**Comment by rofl0r** [comment] 2022-11-04 18:37
duplicate of #481

**Closed by rofl0r** 2022-11-04 18:37 UTC
