### ISSUE TITLE
Proxychains always segfaults

### ISSUE THREAD

**Issue by sinanna** [rofl0r/proxychains-ng#241] opened 2018-06-17 13:07 UTC
Hi everybody,

I was using proxychains-ng on ArchLinux + NordVPN without any problems, but now every application segfaults when launched with proxychains (git):

```
proxychains4 chromium
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.12-git-16-g49d8ac9
[proxychains] DLL init: proxychains-ng 4.12-git-16-g49d8ac9
[proxychains] DLL init: proxychains-ng 4.12-git-16-g49d8ac9
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```
My config is very basic, so it should work:
```
strict_chain
proxy_dns 
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000

[ProxyList]
socks5		193.138.63.146		1080	morrisXX@gmx.de		XX
```

In https://github.com/rofl0r/proxychains-ng/issues/221 there is a problem with NordVPN described, but not with a segfault.

**Comment by rofl0r** [comment] 2018-06-17 16:51
> I was using proxychains-ng on ArchLinux + NordVPN without any problems, but now

what changed between now and then ?

**Comment by rofl0r** [comment] 2018-06-17 16:52
btw chromium does all sorts of tricks to sandbox the code, and is known incompatible with proxychains (see #45 )

**Comment by rofl0r** [comment] 2018-07-13 18:52
closing as duplicate of #45

**Closed by rofl0r** 2018-07-13 18:52 UTC
