### ISSUE TITLE
allow to provide a proxy with a name, not only IP address

### ISSUE THREAD

**Issue by muelli** [rofl0r/proxychains-ng#58] opened 2015-05-06 09:45 UTC
I want to configure a proxy by name, i.e. `http myproxy.acme.corp 8080 user pass`, because my company might change the IP address in the future. Currently, I can only give an IP address.

**Comment by rofl0r** [comment] 2015-05-06 17:02
duplicate of https://github.com/rofl0r/proxychains-ng/issues/25

**Closed by rofl0r** 2015-05-06 17:02 UTC
