### ISSUE TITLE
Let `proxychains-ng` temporarily use the proxy server passed from the command line environment variable instead of through the conf file.

### ISSUE THREAD

**Issue by hongyi-zhao** [rofl0r/proxychains-ng#425] opened 2022-01-20 08:23 UTC
Is this possible: Let `proxychains-ng` temporarily use the proxy server passed from the command line environment variable instead of through the conf file.

Regards,
HZ

**Comment by rofl0r** [comment] 2022-01-20 13:00
duplicate of https://github.com/rofl0r/proxychains-ng/issues/270

**Closed by rofl0r** 2022-01-20 13:00 UTC

**Comment by hongyi-zhao** [comment] 2022-01-21 00:18
A specific example is given [here](https://github.com/rofl0r/proxychains-ng/issues/246#issuecomment-401019706).
