### ISSUE TITLE
doesn't work in macos 12.0.1 (arm64)

### ISSUE THREAD

**Issue by suanve** [rofl0r/proxychains-ng#411] opened 2021-11-01 04:31 UTC
Is there a solution?
![image](https://user-images.githubusercontent.com/35884266/139621921-46c94921-7d04-49b2-bd0b-455a681a1599.png)

**Comment by rofl0r** [comment] 2021-11-01 07:40
duplicate of #409, let's keep the discussion there.

**Closed by rofl0r** 2021-11-01 07:40 UTC
