### ISSUE TITLE
Not working with curl and privoxy

### ISSUE THREAD

**Issue by thomasschmiedl** [rofl0r/proxychains-ng#216] opened 2018-01-19 16:55 UTC
Hello,

I transfer some HLS-streams in xupnpd2 media-server to my TV. xupnpd2 doesn't support https and has no proxy support.

I added a filter-rule in privoxy and tested with curl:
curl --proxy 127.0.0.1:8118 http://hddn01.skylinewebcams.com/live.m3u8?a=0l8pu8egcg6d3ujju5ti33aqv0
This works, URLs in the response were replaced from https to http.

This doesn't work:
bin/proxychains4 -f etc/proxychains.conf curl http://hddn01.skylinewebcams.com/live.m3u8?a=0l8pu8egcg6d3ujju5ti33aqv0
URLs were not replaced in the response.

If someone could test it, query-string is changing and captured from: http://www.skylinewebcams.com/de/webcam/czech-republic/prague/prague/old-town-bridge-tower.html

Thanks for help,
Thomas

**Comment by rofl0r** [comment] 2018-01-19 20:03
what you mean with "URLs were not replaced in the response" and who's supposed to do that ? can you paste some data captured with wireshark ?

**Comment by thomasschmiedl** [comment] 2018-01-19 22:20
I have no experience with wireshark. Here is the privoxy filter/replacement-rule:

in /etc/privoxy/user.filter:
FILTER: test
s@https@http@g

in /etc/privoxy/user.action:
{+filter{test} +force-text-mode}
/.*m3u8

**Comment by rofl0r** [comment] 2018-01-20 14:23
well, then that looks to me as if the issue is on privoxy's side.
since you do not have experience with wireshark and no interest to get some, and i have no experience with privoxy or skylinewebcams and no interest in getting some, i guess we can close this.

**Closed by rofl0r** 2018-01-20 14:23 UTC
