### ISSUE TITLE
Proxychains4 and Python

### ISSUE THREAD

**Issue by wirehack7** [rofl0r/proxychains-ng#55] opened 2015-04-19 10:52 UTC
I recognized that proxychains4 won't work with Pyhton scripts.

Simple IP checking script:

```
#!/usr/bin/python
import urllib, json

data = json.loads(urllib.urlopen("http://ip.jsontest.com/").read())
print data["ip"]
```

Output:

```
$: ./ip.py
2***:4f8:110:312*::2
$: proxychains4 ./ip.py
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
2***:4f8:110:312*::2 # same ip like above
$: curl http://ip.jsontest.com/
{"ip": "2***:4f8:110:312*::2"}
]$: proxychains4 curl http://ip.jsontest.com/
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.8.1-git-11-gba61b48
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  ip.jsontest.com:80  ...  OK
{"ip": "91.109.247.173"}
```

Any hint what causes this and how to resolve this?

**Comment by rofl0r** [comment] 2015-04-21 07:11
pretty sure that the cause is this: https://github.com/rofl0r/proxychains-ng/issues/10#issuecomment-12632041 : glibc's dynlinker does not preserve preloaded DSOs for dlopen'ed modules (that's imo a bug)

**Comment by wirehack7** [comment] 2015-04-21 09:40
So, this will keep broken? I cannot compile everything on my own with musl. Or using that mentioned chroot workaround. 
Pardon me my question, but are there proxy resolutions like proxychains which are working with that? Tsocks seems also to be not working properly.

**Comment by rofl0r** [comment] 2015-04-21 20:45
it's a limitation/bug of glibc dynlinker - to circumvent it use a linux distribution based on musl libc such as alpine linux or void linux or file a bug report for glibc and hope that it gets fixed...

**Comment by kentrosi** [comment] 2018-10-25 20:48
Using python3

`proxychains4 python test.py`

```python
import requests
r = requests.get("https://ipinfo.io/ip")
print(r.content)
```
returns correctly. 

It's a little more complex with selenium.

**Comment by kentrosi** [comment] 2018-10-25 22:58
Using python3 and python2

`proxychains4 python test.py`

```python
import requests
r = requests.get("https://ipinfo.io/ip")
print(r.content)
```
__Returns__:
```bash
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.13-git-3-geb36238
[proxychains] DLL init: proxychains-ng 4.13-git-3-geb36238
[proxychains] Strict chain  ...  177.*.*.*:8080  ...  ipinfo.io:443  ...  OK
b'177.*.*.*\n'
```
```bash
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.13-git-3-geb36238
[proxychains] Strict chain  ...  212.*.*.*:56413  ...  ipinfo.io:443  ...  OK
b'212.*.*.*\n'
```

__Distro__:
- OS X 10.11.6 - 10.14
- Debian 9 
    - glibc 2.27
- CentOS 7
    - glibc 2.17

**Comment by rofl0r** [comment] 2018-10-25 23:01
thanks @kentrosi  for testing, in that case we can close this..

**Closed by rofl0r** 2018-10-25 23:01 UTC
