### ISSUE TITLE
proxychains4 .16 on mac m1

### ISSUE THREAD

**Issue by NaliangzzZ** [rofl0r/proxychains-ng#509] opened 2023-05-06 15:23 UTC
OS:Mac m1 Ventura
ProxychainsVersion:4.16
Use commonds:
`git clone https://github.com/rofl0r/proxychains-ng.git`
`cd proxychains-ng`
`./configure --fat-binary-m1`
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/48352060/236633014-cfa8e58b-c359-4031-8088-ee108b3f4cfa.png">

**Comment by NaliangzzZ** [comment] 2023-05-06 15:25
I fogot some commands, After `./configure --fat-binary-m1`
`sudo make`
`sudo make install`
`proxychains4 curl baidu.com`

**Comment by rofl0r** [comment] 2023-05-06 19:32
duplicate of #481

**Closed** 2023-05-06 19:32 UTC

**Comment by coldinke** [comment] 2023-05-08 06:44
@NaliangzzZ This problem can be solved by using the method dexcribed in this link: This problem can be solutioned use the link https://github.com/rofl0r/proxychains-ng/issues/481#issuecomment-1455369572"
