### ISSUE TITLE
proxychains-ng doesn't work with ssh on Ubuntu 22.04

### ISSUE THREAD

**Issue by lbmeng** [rofl0r/proxychains-ng#450] opened 2022-05-14 16:11 UTC
On Ubuntu 22.04, proxychains-ng doesn't work again with ssh:

```
$ proxychains4 ssh git@github.com
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
select2: Bad file descriptor
ssh: Could not resolve hostname github.com: Unknown error
```

Other commands (e.g.: wget) work with proxychains-ng correctly.

**Comment by rofl0r** [comment] 2022-05-15 08:41
duplicate of #439

**Closed by rofl0r** 2022-05-15 08:41 UTC
