### ISSUE TITLE
Proxychains4 with brew for MacOs error

### ISSUE THREAD

**Issue by bobbuilder123** [rofl0r/proxychains-ng#109] opened 2016-02-22 20:30 UTC
Here is the error:
MacBook-Pro:~ Bob$ proxychains4 nmap -sS 192.168.5.1
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.11/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib
dyld: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib' because no suitable image found.  Did find:
    /usr/local/Cellar/proxychains-ng/4.11/lib/libproxychains4.dylib: mach-o, but wrong architecture
Any idea what to do? Here is my question asked on superuser: https://superuser.com/questions/1029102/how-to-install-proxychains-for-mac-os/1044016

**Comment by rofl0r** [comment] 2016-02-22 23:11
try to run configure with ```--fat-binary``` i.e. ```./configure --fat-binary ...```
you may have to change that in the homebrew recipe.

**Comment by bobbuilder123** [comment] 2016-02-23 02:09
I installed proxychains with brew

**Comment by bobbuilder123** [comment] 2016-02-23 02:40
I installed it and it now seems to work but when I run: proxychains4 open -a /Applications/Firefox.app http://whatsmyip.org, it would print my real ip. Would you have an idea why?

**Comment by bobbuilder123** [comment] 2016-02-23 04:29
I have a question I must ask: when performing a syn scan on https://www.google.ca, I can see that the destination is indeed 184.150.182.231 (google's ip) and not my tor's proxy. Would you know why? Is it something I did not understand about networking or would it be a normal behavior?

**Comment by rofl0r** [comment] 2016-02-23 09:12
it's normal behaviour that google has google's ip.
however whatsmyip should print the ip of the proxy. it probably works if you run the firefox binary directly i.e. ```proxychains4 /Applications/Firefox.app/name_of_binary_here``` or if you just change the proxy settings directly in firefox (i.e. without using proxychains).

**Comment by leebaird** [comment] 2016-09-01 19:56
Still having the same issue with v4.11

**Comment by XasaKura** [comment] 2016-09-16 10:43
I have  use  `brew install  proxychains-ng --universal`  but still have the same issue with v4.11

PS:
output:
```
==> ./configure --prefix=/usr/local/Cellar/proxychains-ng/4.11 --sysconfdir=/usr/local/Cellar/proxychains-ng/4.11/etc --fat-binary
checking whether netinet/in.h defines s6_addr16 ... no
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... yes
checking whether $CC defines __OpenBSD__ ... no
Configuring a fat binary for i386 and x86_64
Done, now run make && make install
```

**Comment by rofl0r** [comment] 2016-09-16 18:10
@XasaKura your PS output above seems to miss the output of make (compiler invocations etc). did you leave that away intentionally ?

**Comment by XasaKura** [comment] 2016-09-17 04:55
@rofl0r   I only copy the part of `configure`

**Comment by rofl0r** [comment] 2016-09-17 12:58
well, in that case it is weird. maybe pastebin the entire output of running the brew install command to give us more clues what went wrong. i'm reopening this until we can rule out that there's something wrong on our side.

**Comment by awar** [comment] 2016-10-26 10:48
@bobbuilder123 This can resolve your problem.
uninstalling your proxychain on brew with rmtree and install again this way `brew install proxychains-ng --universal`

**Comment by yangnw** [comment] 2016-10-26 13:30
same problem here.
first, installed with brew without --universal. works but not with system bins. 
then disabled SIP. works for a few minutes after startup. but then quite suddenly this error shows up.
brew remove and brew install --universal, but still doesn't work.
cloned and ./configure --fat-binary. still doesn't work.

I will reenable SIP to see if this is fixed.

**Comment by yangnw** [comment] 2016-10-26 13:36
./configure --fat-binary
`checking whether netinet/in.h defines s6_addr16 ... no
checking whether netinet/in.h defines __u6_addr.__u6_addr16 ... yes
checking whether $CC defines __OpenBSD__ ... no
Configuring a fat binary for i386 and x86_64
Done, now run make && make install`

make
`cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/version.o src/version.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/allocator_thread.o src/allocator_thread.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/ip_type.o src/ip_type.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/hostsreader.o src/hostsreader.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/hash.o src/hash.c
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/debug.o src/debug.c
cc -fPIC  -ldl -lpthread -arch i386 -arch x86_64 -Wl,-install_name,libproxychains4.dylib  \
		-shared -o libproxychains4.dylib src/nameinfo.o src/version.o src/core.o src/common.o src/libproxychains.o src/allocator_thread.o src/ip_type.o src/hostsreader.o src/hash.o src/debug.o
cc -DSUPER_SECURE -Ds6_addr16=__u6_addr.__u6_addr16 -Ds6_addr32=__u6_addr.__u6_addr32 -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -arch i386 -arch x86_64 -DLIB_DIR=\"/usr/local/lib\" -DSYSCONFDIR=\"/usr/local/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/main.o src/main.c
cc src/main.o src/common.o  -o proxychains4`

csrutil status
`System Integrity Protection status: disabled.`

./proxychains4 brew update
`[proxychains] config file found: /Users/Yang/.proxychains/proxychains.conf
[proxychains] preloading ./libproxychains4.dylib
dyld: warning: could not load inserted library './libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	./libproxychains4.dylib: code signing blocked mmap() of './libproxychains4.dylib'
dyld: warning: could not load inserted library './libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	./libproxychains4.dylib: code signing blocked mmap() of './libproxychains4.dylib'
dyld: warning: could not load inserted library './libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	./libproxychains4.dylib: code signing blocked mmap() of './libproxychains4.dylib'
^C`

**Comment by awar** [comment] 2016-10-26 13:43
@yangnw have you uninstalled with rmtree `brew rmtree proxychains-ng` if you haven't rmtree package you can install it whit `brew tap beeftornado/rmtree && brew install brew-rmtree ` and next install `brew install proxychains-ng --universal`. I have osx yosemite and work correctly

**Comment by yangnw** [comment] 2016-10-26 13:52
re-enabled SIP and restarted, now works again.
but system binaries do not work now, as before I disabled SIP. 

@awar it's probably due to macOS Sierra messing with SIP or something.

**Comment by lucklove** [comment] 2016-11-16 15:58
The same with me.

**Comment by yangnw** [comment] 2016-11-18 02:57
@HTNecro @lucklove I've disabled SIP, and now it works as long as it's not a binary in /usr/bin and other system paths that's being called. for example, to use curl over proxychains, I have to either move the curl binary somewhere else in the path, or use `proxychains4 wget -O - $url`.
Same behavior regardless built from source or homebrew build. This should have nothing to do with homebrew.

**Comment by yangnw** [comment] 2016-11-27 08:38
@HTNecro update: brew seems to use to the system curl regardless of the path, so I have to run etc. `ALL_PROXY=socks5://127.0.0.1:1080 brew upgrade` to get it working.

**Comment by crapthings** [comment] 2017-01-12 06:13
open terminal with osx recovery mode

```
csrutil disable
reboot
```

```
brew tap beeftornado/rmtree && brew install brew-rmtree
brew install proxychains-ng
```

~/.proxychains/proxychains.conf

```
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
quiet_mode

[ProxyList]
socks5  127.0.0.1 1080
```

```
csrutil enable
```

**Comment by motecshine** [comment] 2017-01-12 11:07
@crapthings  its work for me

**Comment by jinfagang** [comment] 2017-03-22 11:37
same issue, I think I am going f**ked up by this anoying problem. Any one occured this on macOS sierra?

**Comment by louisabraham** [comment] 2017-04-03 00:08
@jinfagang I had no problem two months ago, but now have the same issue…

**Comment by rofl0r** [comment] 2017-04-03 12:36
please report homebrew issues to the homebrew issue tracker, thanks!

**Comment by louisabraham** [comment] 2017-04-03 12:40
Actually, I solved this problem by build from source. On OS X you just have to change 

    bindir=/usr/local/bin
    libdir=/usr/local/lib

in config.mak, then

    ./configure --fat-binary
    make
    make install

**Comment by rofl0r** [comment] 2017-04-03 12:43
running configure will overwrite config.mak, so it was probably the other way round.
also you can pass bindir and libdir as parameters to configure, so you dont have to edit at all:
```
./configure --prefix=/usr/local --bindir=/usr/local/bin --libdir=/usr/local/lib --fat-binary
```

**Comment by gregakinman** [comment] 2017-04-06 14:40
The above steps did not work for me on OS X 10.11.6...

**Comment by louisabraham** [comment] 2017-04-06 14:53
@gregakinman what is your error message?

**Comment by gregakinman** [comment] 2017-04-06 15:28
@louisabraham 

    $ proxychains-ng/proxychains4 ./gradlew idea --no-daemon
    [proxychains] config file found: /usr/local/etc/proxychains.conf
    [proxychains] preloading proxychains-ng/libproxychains4.dylib
    proxychains can't load process....: Permission denied

**Comment by louisabraham** [comment] 2017-04-06 17:34
@gregakinman That's absolutely not the same problem! Use ```sudo```

**Comment by iFurySt** [comment] 2017-04-10 05:03
`brew install proxychains-ng --universal`
it work for me (macOS Sierra 10.12.3)

**Comment by gregakinman** [comment] 2017-04-10 10:17
$ brew install proxychains-ng --universal
    Warning: proxychains-ng: this formula has no --universal option so it will be ignored!

    $ brew --version
    Homebrew 1.1.12
    Homebrew/homebrew-core (git revision 600f; last commit 2017-04-10)

**Comment by cnlonlyrain** [comment] 2017-04-22 06:12
@louisabraham It works for me thanks!

**Comment by geekwutom** [comment] 2017-07-05 06:55
The above steps did not work for me on OS X 10.12.5..

**Comment by rofl0r** [comment] 2017-07-06 14:39
> The above steps did not work for me on OS X 10.12.5..

that's pretty vague. post more details, including brew output and error messages you get when using it. someone using mac may be able to figure out what's wrong, @geekwutom

**Comment by zhilevan** [comment] 2017-09-25 06:11
I've tried all solutions in MAC OS but no one works for me and still facing with 

> proxychains4 curl twitter.com
> [proxychains] config file found: /usr/local/etc/proxychains.conf
> [proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12_1/lib/libproxychains4.dylib

**Comment by rofl0r** [comment] 2017-09-25 12:27
@zhilevan i can't see anything wrong in the output you posted

**Comment by byp4ss** [comment] 2018-04-22 06:55
i am same



```
proxychains4 git --version
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.12-git-15-gbb30d86
dyld: warning: could not load inserted library '/usr/local/lib/libproxychains4.dylib' into library validated process because no suitable image found.  Did find:
	/usr/local/lib/libproxychains4.dylib: code signing blocked mmap() of '/usr/local/lib/libproxychains4.dylib'
	/usr/local/lib/libproxychains4.dylib: stat() failed with errno=1
git version 2.15.1 (Apple Git-101)
```

macOS 10.13.4
Homebrew 1.6.1
System Integrity Protection status: disabled.

Use curl can work,
but i run git,error

**Comment by rofl0r** [comment] 2018-07-13 19:09
closing as duplicate of #78

**Closed by rofl0r** 2018-07-13 19:09 UTC

**Comment by NightMachinary** [comment] 2019-06-20 09:08
```
[proxychains] config file found: /Users/evar/.proxychains/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
dyld: warning: could not load inserted library '/usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib' into hardened process because no suitable image found.  Did find:
	/usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: code signature in (/usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: stat() failed with errno=1
```

**Comment by rofl0r** [comment] 2019-06-20 13:06
could people please stop to resurrect 3 year old zombie issues ? and then posting no useful information at all at that ?
