### ISSUE TITLE
I try to proxy brew update, but it failed

### ISSUE THREAD

**Issue by EVINK** [rofl0r/proxychains-ng#393] opened 2021-08-12 04:38 UTC
my mac SIP is already disabled, could you give me any help here?
    
    proxychains4 brew update
    [proxychains] config file found: /opt/homebrew/etc/proxychains.conf
    [proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
    [proxychains] DLL init: proxychains-ng 4.14
    dyld: could not load inserted library '/opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib' because no suitable image found.  Did find:
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: incompatible cpu-subtype: 0x00000000 in /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: stat() failed with errno=1
    
    dyld: could not load inserted library '/opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib' because no suitable image found.  Did find:
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: incompatible cpu-subtype: 0x00000000 in /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: stat() failed with errno=1
    
    dyld: could not load inserted library '/opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib' because no suitable image found.  Did find:
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: incompatible cpu-subtype: 0x00000000 in /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib
	    /opt/homebrew/Cellar/proxychains-ng/4.14/lib/libproxychains4.dylib: stat() failed with errno=1
    
    [1]    20264 abort      proxychains4 brew update

**Comment by rofl0r** [comment] 2021-08-12 05:32
duplicate of #357 - unfortunately the comments there are unconclusive. you might want to try what's suggested there and report back.

**Closed by rofl0r** 2021-08-12 05:32 UTC
